const MessageTypes = {
    SEND_NODES: 'SEND_NODES',
    PROGRESS_UPDATE: 'PROGRESS_UPDATE',
    PROFILE_LOADED: 'PROFILE_LOADED',
    NODE_FETCHED: 'NODE_FETCHED',
    TRANSFER_PROFILE: 'TRANSFER_PROFILE',
    APPLY_FILTERS: 'APPLY_FILTERS',
    FETCH_NODE: 'FETCH_NODE',
    TRANSFER_COMPLETE: 'TRANSFER_COMPLETE'
};

export default MessageTypes;